name: Tag Release
on:
  issue_comment:
    types: [created]
    branch: stable 
jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: release
          reaction: "true"
          reaction-type: "rocket"
          allow-edits: "false"
          permission-level: admin
      - name: Tag this release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y.%m.%d")
          PREV_RELEASE=$(git tag --list | tail -1)
          MINOR_VERSION=0
          if [[ "$PREV_RELEASE" == *"$DATE"* ]]; then
              MINOR_VERSION="$PREV_RELEASE" | cut -d'.' -f5
              let MINOR_VERSION++
          fi
          TAG="r.$DATE.$MINOR_VERSION"
          git log $(git tag --list | tail -1)..$GITHUB_REF | git tag -a $TAG -F -
          git push origin $TAG
        shell: bash
